export default {
	backgroundLight: "#EBEBEB",
	backgroundDark: "#323234",
	backgroundLightHighlight: "#FFFFFF",
	backgroundDarkHighlight: "#C4C4C4",
	backgroundLightHighlightFloat: "#FFFFFFDF",
	backgroundDarkHighlightFloat: "#C4C4C4CC",
	backgroundLightHighlightSoft: "#FFFFFF40",
	backgroundDarkHighlightSoft: "#C4C4C440",
	backgroundAccent: "#FF312E",
	backgroundApprove: "#46866F",
	typographyLight: "#FFFFFA",
	typographyDark: "#000103",
	typographyAccent: "#FF312E",
	typographyApprove: "#46866F",
};
